@startuml Use case diagram

actor User as U
actor "S32K144" as B

usecase "View Media Files" as UC1
usecase "Manage Playlists" as UC2
usecase "View/Edit Metadata" as UC3
usecase "Play Media" as UC4
usecase "Control Volume" as UC5
usecase "Connect External USB" as UC6
usecase "Control via Board" as UC7
usecase "Display Song Info on Board" as UC8

U --> UC1 : Browse Media Files
U --> UC2 : Create/Update/Delete
U --> UC3 : View Metadata
U --> UC3 : Edit Metadata
U --> UC4 : Play/Pause/Next/Previous
U --> UC5 : Adjust Volume
U --> UC6 : Mount & Parse USB

B --> UC5 : Adjust Volume (ADC)
B --> UC4 : Play/Pause/Next/Previous
B --> UC8 : Show Song Info

@enduml